# Re-exports every public name — callers use `import queries; queries.fn()` unchanged.
from queries._shared import (
    current_year as current_year,
    prior_year as prior_year,
    display_years as display_years,
    max_luna_for_year as max_luna_for_year,
    get_sku_cod_mare_map as get_sku_cod_mare_map,
    rebuild_cond_resolved as rebuild_cond_resolved,
    ensure_cond_resolved as ensure_cond_resolved,
    furnizori_list as furnizori_list,
    agents_list as agents_list,
    brands_list as brands_list,
)
from queries.analytics import (
    kpi_cards as kpi_cards,
    kpi_luna_curenta as kpi_luna_curenta,
    monthly_trend as monthly_trend,
    brand_mix as brand_mix,
    channel_mix as channel_mix,
    risk_kaufland as risk_kaufland,
    risk_agent as risk_agent,
    churn_clients as churn_clients,
    top_clients as top_clients,
    team_table as team_table,
    agent_kpi as agent_kpi,
    agent_monthly_trend as agent_monthly_trend,
    agent_clients as agent_clients,
    agent_top_skus as agent_top_skus,
    agent_clients_full as agent_clients_full,
    agent_brands_full as agent_brands_full,
    agent_skus_full as agent_skus_full,
    agent_brand_sku_monthly as agent_brand_sku_monthly,
    agent_monthly_full as agent_monthly_full,
    agent_monthly_base as agent_monthly_base,
    agent_monthly_all_years as agent_monthly_all_years,
    agent_brand_monthly as agent_brand_monthly,
    profitabilitate_agenti as profitabilitate_agenti,
    profitabilitate_clienti as profitabilitate_clienti,
    profitabilitate_produse as profitabilitate_produse,
    profitabilitate_matrice as profitabilitate_matrice,
)
from queries.clients import (
    clients_list as clients_list,
    client_info as client_info,
    client_orders as client_orders,
    client_brand_mix as client_brand_mix,
    client_yearly as client_yearly,
    client_products_full as client_products_full,
    client_yearly_full as client_yearly_full,
    client_monthly_full as client_monthly_full,
)
from queries.products import (
    products_brands as products_brands,
    products_top_skus as products_top_skus,
    brand_monthly_full as brand_monthly_full,
    brand_kpi as brand_kpi,
    brand_clients as brand_clients,
    product_kpi as product_kpi,
    product_clients as product_clients,
    product_monthly as product_monthly,
    product_yearly as product_yearly,
    sku_clients_monthly as sku_clients_monthly,
)
from queries.pricing import (
    preturi_catalog as preturi_catalog,
    preturi_sku as preturi_sku,
    preturi_client_sku as preturi_client_sku,
    preturi_update_landing as preturi_update_landing,
    preturi_update_vanzare as preturi_update_vanzare,
    preturi_update_produs as preturi_update_produs,
    rate_schimb_list as rate_schimb_list,
    rate_schimb_update as rate_schimb_update,
    conditii_list as conditii_list,
    conditii_get as conditii_get,
    conditii_create as conditii_create,
    conditii_update as conditii_update,
    conditii_delete as conditii_delete,
    termene_list as termene_list,
    termene_create as termene_create,
    termene_delete as termene_delete,
    marja_ajustata as marja_ajustata,
)
from queries.orders import (
    termene_aprovizionare_list as termene_aprovizionare_list,
    termene_partial_update as termene_partial_update,
    termene_aprovizionare_upsert as termene_aprovizionare_upsert,
    comenzi_list as comenzi_list,
    comanda_get as comanda_get,
    comanda_create as comanda_create,
    comanda_update as comanda_update,
    comanda_delete as comanda_delete,
    comanda_line_upsert as comanda_line_upsert,
    comanda_line_update as comanda_line_update,
    comanda_line_delete as comanda_line_delete,
)
from queries.forecast import (
    forecast_stoc as forecast_stoc,
    forecast_summary as forecast_summary,
    forecast_gama_list as forecast_gama_list,
    forecast_stoc_brand as forecast_stoc_brand,
    forecast_stoc_extended as forecast_stoc_extended,
    forecast_brands_list as forecast_brands_list,
    basilur_monthly_per_brand as basilur_monthly_per_brand,
    basilur_kpi_per_brand as basilur_kpi_per_brand,
    basilur_kpi_total as basilur_kpi_total,
    basilur_stoc_per_brand as basilur_stoc_per_brand,
    basilur_stoc_total as basilur_stoc_total,
    basilur_stoc_detail as basilur_stoc_detail,
    basilur_monthly_trend as basilur_monthly_trend,
)
from queries.bonus import (
    bonus_team as bonus_team,
    bonus_agents as bonus_agents,
    lunar_config as lunar_config,
    obiective as obiective,
    payout_grid as payout_grid,
    realizat_auto as realizat_auto,
    realizat_brand as realizat_brand,
    py_baseline as py_baseline,
)
from queries.export import (
    get_export_hu_codes as get_export_hu_codes,
    monthly_sales_ro_hu as monthly_sales_ro_hu,
    stoc_ro_hu as stoc_ro_hu,
    in_transit_ro_hu as in_transit_ro_hu,
    expirare_list as expirare_list,
    tari_export_list as tari_export_list,
    tari_export_upsert as tari_export_upsert,
    tari_export_delete as tari_export_delete,
    clienti_export_list as clienti_export_list,
    clienti_export_upsert as clienti_export_upsert,
    clienti_export_toggle as clienti_export_toggle,
)
